### ISSUE TITLE
please display the saved connection name

### ISSUE THREAD

**Issue by aokolish** [woollyapp/woolly#2]
When connecting to heroku databases, it would be nice if I could see the name of the saved connection so that I can more easily tell which app I am connected to (e.g. staging or production).

![pasted_image_10_4_13_11_22_am](https://f.cloud.github.com/assets/705514/1271815/0f5a3f00-2d22-11e3-95ce-8329aa12a39f.png)

**Comment by kevintom** [comment]
updated and new version has been released
