### ISSUE TITLE
query highlighting can get messed up when editing an existing line

### ISSUE THREAD

**Issue by aokolish** [woollyapp/woolly#3]
![pasted_image_10_7_13_10_30_am](https://f.cloud.github.com/assets/705514/1282589/8a3eb2d6-2f76-11e3-9fad-6008933c9049.png)

**Comment by kevintom** [comment]
still investigating, but may be related to other syntax highlighting issue.

**Comment by kevintom** [comment]
Fix has been approved and new version has been released
