### ISSUE TITLE
Can't tell Heroku apart from local

### ISSUE THREAD

**Issue by datachomp** [woollyapp/woolly#6]
This is a bit personal/cosmetic:

On the connections pane, it would be nice if saved Heroku connections had a different connection icon/group/something to differentiate from standard connections.

Currently, I am going back and prefixing a Heroku_  to the name of the connection but it's a bit cumbersome for something that could be handled by the fact I'm already on the 'heroku' connection settings. Thoughts?

**Comment by kevintom** [comment]
good idea,

i'll look into adding this, 

thanks for the feedback
